Fixed composer hash check in build container dockerfile

diff --git a/build/Dockerfile b/build/Dockerfile
--- a/build/Dockerfile
+++ b/build/Dockerfile
@@ -8,18 +8,20 @@ ENV DEBIAN_FRONTEND noninteractive
 
 # install runtime environment
 
-RUN apt-get -q update
-RUN apt-get -qy --no-install-recommends install \
+RUN apt-get -q update && \
+    apt-get -qy --no-install-recommends install \
 	php${PHP_VER}-cli \
 	php${PHP_VER}-mysql \
 	php${PHP_VER}-xml \
 	php${PHP_VER}-zip \
 	git \
-	ca-certificates
+	ca-certificates \
+	wget
+ 
+RUN EXPECTED_SIGNATURE="$(wget -q -O - https://composer.github.io/installer.sig)" && \
+    php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" && \
+    ACTUAL_SIGNATURE="$(php -r "echo hash_file('sha384', 'composer-setup.php');")" && \
+    if [ "$EXPECTED_SIGNATURE" != "$ACTUAL_SIGNATURE" ]; then >&2 echo 'ERROR: Invalid installer signature'; rm composer-setup.php; exit 1; fi
 
-# composer
-
-RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
-RUN php -r "if (hash_file('SHA384', 'composer-setup.php') === '669656bab3166a7aff8a7506b8cb2d1c292f042046c5a994c43155c0be6190fa0355160742ab2e1c88d40d5be660b410') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
-RUN php composer-setup.php
-RUN php -r "unlink('composer-setup.php');"
+RUN php composer-setup.php --quiet && \
+    rm composer-setup.php
